name: Go

on:
  push:
    branches: [ "feature/golang" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: |
        cd golang
        go build -v ./...

    - name: Test
      run: |
        cd golang
        go test -v ./...
